[[asdf_cxx]]
arch = "aarch64"
git-tree-sha1 = "8427f39762bfe4fbadd8c1a63a840bb5d0f1cd1e"
os = "macos"

    [[asdf_cxx.download]]
    sha256 = "90781b91641b46aaad6b7581e9ea39acf36ed291e28150f1c4d22e0d0014fea0"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.aarch64-apple-darwin.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df3ce3936f7561d4f4925b72df72ad3af67b4c0"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "19b875e4536909c3600d1b0662cb051fe037d1adef9dc02ea4085f315206d459"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb10ce9a6d7878301baae39ed5bbb6542f98c64f"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "d7fc14def8524df43c13dbc64b324b0f1499f68f67833e11d975abc634db3367"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bd297bf1b1889b9bb993a34a3deba88f46612ce"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "fdbc3cf89eb4ac94a02fff428530bcc32e71a3ab662dd5813d63dd0cfe74e96f"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d16dc5491f1331903f0cf97d9672c7ce07dfebb8"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "b212ce770406b9b7530a3f68186037266430d83d8cb6f710ebd3b37c1138c7bb"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05460ffff39f736749a39e1128a17ead1189ec7e"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "2bd06bac28664cdb3cd674b1f410ed5f6b73fe3f50963ea08b6049222e94fa81"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38372c07df8bc7750889ed261daa122ae21882b1"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "94c36eb06fe7f1fd1fff8745853063cbd9a276c278f1a12098c2d33206787893"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0affc4bf84e517bb0466a954567740f44922c29"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "ad6e97e4ef28fcb71cb8a9f4299fb04dfc7f083b380aac1742fb70894f6a58c8"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "580a4fa42c199fca2658ba2d67906bb106336d1c"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "45640457ce9425afbdf76a960350d1ce00f5b0435732f47feece408d71aec62e"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcab6d633c251289d598df38ef1ee74daf8a9ae4"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "827d3615ce509131081a85e0f6f654988b0db40e6843979e2965538895b2a30e"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cd8be722020386ae13235ec0a04b2576d6e24ad"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "ff0521fd8bb4cc1be203cd2f8ef7fab5c6628d950fd2c8960e4c24134f5f9e20"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef0d5d844ba625899a438b68441b97ae7212500c"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "1feb4b30d36f647e2034f03c709512878261f3e74ebc36687e7f3e085b54f073"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "793a184b242f30e14d0653505d13d7427140364e"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "1a53b712c5fb78a73cf7939773a3332e1828772a07cddd435ea79ca5bad3a9ed"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e9ef90b2602070e094f5fe3e4169abba70d01ae"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "09341bbd612f45b6751fbea9a7dcbad195be5835ced663084d12e6fc37b43ef7"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.i686-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81be1d2c48440e8dbd7625630694d36875202af0"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "73cc3993dfb6d53fc8d24f0c18340168c33adb9e65d42d79ab97b016ac2cb0e7"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.i686-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef1bbe72624f347b01a4975edd2992aa4e093839"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "b4b8a4868a4a8efc46c1c8b5b122fbb0e48d47d868c931e8e77e1b6474514e80"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.i686-linux-musl-cxx03.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41cc3560d9f2f5673cf1156313a1d37f9d305c1e"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "5833976f90c16e12e373385b9a093381efb224c3fa417c3b7b3622af47fe2227"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.i686-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2950dbba3f6883276e25d2a23bcd1ba0cfacd799"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "a7c09be1084569e041179d1db01fe883fc8593d7dd304773e5ee16ebd690d592"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.i686-w64-mingw32-cxx03.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b5d316d356d5799b42d319d268cd35655101ef3"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "d286efbcca450f9e9431c16ea05654bfe34b5bfdb8fc4c13fc872f2afb706aa5"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.i686-w64-mingw32-cxx11.tar.gz"
[[asdf_cxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4400547e590ae17fb013c780b51362b683a0798"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "56504ceebd2b15c1e279e828ca1b037cd4534b840fa11d1dd7c3de98fce3ee4a"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fa86c3a31486bca37d47dd231209ff8e1dd2fbe"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "df1a2297c32715cbd884e297a763e575b2aa7e7db93b5954145253d656cd4756"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
git-tree-sha1 = "05f7d92e9e6d72f7daf0225092c2c5956b1cdf7a"
os = "macos"

    [[asdf_cxx.download]]
    sha256 = "b1c97816252a2f3b9da9452ecaf18022fed4ed30a9f63c3d93de11b3df16eca5"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-apple-darwin.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a88324990d537c93a23e5af7e11c05d55a94c42"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "8a5e0ffaed8cc6ae7d2bee31929ba703fdb65b073d1f5068e6a76386892c5d15"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2deaf8c523bf1061ec5fa9a5ed6b01781a52d098"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "79454f174b0b808f7f30bbc9341466f65c7d0a340f6f89bd9b5533fe504d4679"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38bf7fb0648cce83e79f468b3dc2f52e10363796"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "8bb3b8346da75e4118aaafe6e709b1426984eb5701084d6f7516fe16263db444"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c47625105e0d04e4dae86767e2e807bea6240c58"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "abb7a39c3740c5fac11ecb3b12ccaa9fd1f2b05daf44441fa9e7abc63d638cc1"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
git-tree-sha1 = "9a417b22bcbe493b735e2baa483ab222ba7be1e0"
os = "freebsd"

    [[asdf_cxx.download]]
    sha256 = "7546a472828f6ad087f5c680d90c30f0625470594a843d5d3ebe0f77ee2d8d94"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-unknown-freebsd.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b204164894f38f3947e8325d36f40a10d70b9a71"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "13c43f235797426bbf399373b7ccb870c8a81286be8316ad3e81e44adf56d5e1"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8811d115351753037efac874b06edf66ac660c4"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "e07748d6470297fb9732e5cbf4a84e959d64e745150ec293232c74843a6f5f84"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.2+0/asdf_cxx.v7.3.2.x86_64-w64-mingw32-cxx11.tar.gz"
