[[asdf_cxx]]
arch = "aarch64"
git-tree-sha1 = "9b66cc118650b47c8f357c150b4d488209da8dfa"
os = "macos"

    [[asdf_cxx.download]]
    sha256 = "99230cf0ef64bc673b6a9a9b32655692fd7b4369d8df3ccb0e7d0f20e8d5b02d"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.aarch64-apple-darwin.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa84b41e1bcacdf9762639e131279c367068e082"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "92887bb96b80e1b471ec99512ce569a85554718afba5f4a8d17397916edfa2e1"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76355f256128d226d98deaacf7a9ce045cffc433"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "cd03cd37f041b6cee4633d6835fa662270967286ee1bb3c2474796f494c77e69"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06b45cb1bef6148335ee013114236521473c2ae3"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "5e92bc1bf839d4bd710e002bcd84963079d72dbfd4e286295235396846eb3b86"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfecbdd517f0e8cd8905c01f944ebc001a30e5e9"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "4a810c2b27831e2e872aa8260ac2116290be079ab913d8f336d7e9db90a74cde"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8b7fe1ea739a3f12e1d80b4a775ab279456d37e"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "53f7103428509ac60b3b89f7801e2b6beea9f4ecb835f0ce12d570ba9dea7e71"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c459490ba6caca9393ba0c5bf6ce5123a0e5b4e7"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "f093fe6313acfcba9971b657fdd23c65e3dc3ecb9a29ee8b36f2c9d58d9ddd8f"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faab27b759cfd21217fd853a7a7f78c2b619dc6c"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "8f45a35010d21c593d463ae2d043861fc4ab20d3a2799607b6bba5f69cb29c44"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a27583715909071ba244f8b176d40369bc7da51b"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "ba0d0bec9aa25971dcbdd614ba3da374d1acfd328863a4bc4be54c219a3aac49"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b173bd8c4b9c8d4b54c9a4e14533b3e3951593d"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "c4d747ca63fb3301d65a76baab49bf21630fc3cfd60fc82d74f8abb61a8fc716"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a6f62f5d3441c670d74159bc8b2f64eb17bdc0e"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "a32514ff3db2019a0bbb6e43c9198d3c15ccab6bcc0771d410d27526b28fb2c2"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f2d03c65700124ed968475e5f56c0090bc9ae5f"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "83cb5af784b4516c787da7957c838680fd08da0bb2484adbebb22e43b5f74df1"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92dd0fc95e6803d77def55d1ba3310e11d82703f"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "a9d85bb0195f8001ddd436bf64b3935154497ad6c6904a740106ad26acf785a3"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1493e1ed2ea26ac87f4dd7017b0aaeb17a7d4934"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "07dc2c6a616531eaa21431a9de9226aa02e8d7091b848201da8c821ce0c81af4"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.i686-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71e3743b378661821d7a74f180c6a55a233a7e0c"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "4852103f4989f9dbd3e120dea49b16f4780e7bae455fd49ee01bc551bc996bab"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.i686-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b0aa8e85f5dc0dc654649e63313749e6a69d3fe"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "ae577a715c488dc87fe2b99147429bd2f308baa98db796d32da21c2d2b19d3ba"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.i686-linux-musl-cxx03.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abb35c51c0f67e2bd4ef84bd66a51fa7c6574d33"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "42743902a0df54919bf837bd2678db55aa0095c2b5bc0de1cf7dfa6bf0867a53"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.i686-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca16dfb2571bce405b66d6e5393d973d233623fc"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "f3b8dfdf2819ad1eecee398a98710b019d1556614b7c6a16ea375b011cce259e"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.i686-w64-mingw32-cxx03.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c278c5429bc6bdb64a1dd4f198f010dc35281191"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "24b0ab83628c173dc023bcfc64c0f5157151a73586e943acd92df15c978b00b7"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[asdf_cxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9a0d2bb543811e5f20c7cd8339b081c2bba290b"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "2fc10d2bb355133b9d78259c87c5d855f63a4e6ad8942d76a418b61dbabe5276"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "677c371459072dbfc6e72927b6f0725a125cb0de"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "ab9b3099f5fd62c4c6c0380fe011784c02c96b784dcd6c1880d6ab91b22c54b4"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
git-tree-sha1 = "142f395d58efcea544f8ffa958ca8604f4a3b3c0"
os = "macos"

    [[asdf_cxx.download]]
    sha256 = "78485cd78ada90705a7334f237f26d1d591ab2f1105049f95140a1b22b33c217"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-apple-darwin.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13578e45807ea0a97012ab91592d473525a12a62"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "b890dd3cb52f0af3870467f9d81aa162b0849cbc1db16d165f17c9212ff093b7"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26dd9c9b579fae93adbc1b692f51d532c4252a8e"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "c573829ab1cf2b3a5f7175bd59a46533ffe74557614fdcd9e7f72a114b5036e3"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6f3a9bba90caefe26fae47f97cb43943d380d13"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "baaf1c2547c265c81797ece8e9912607ec4287201345f1a209b3dcb1f4069d2e"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71c30c369be4b3dd16e052512308d2b1890cb699"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "27f5e2c6a1abedf40fbb288e6e774a4016094c47406842a2617c6ab75c733911"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
git-tree-sha1 = "aee1e56bc2bf63008f180ea43ded8951ffb76eec"
os = "freebsd"

    [[asdf_cxx.download]]
    sha256 = "49bc4b6cbce2de41baadd3ff126cca6d053e9b57c491ef64e538bbe219c600db"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-unknown-freebsd.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efac47d2db6e01ec7c6d60a810c43dd1c1616d3c"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "c8c2f63cf24b92b53651af6d8ec56aaa4f871c32d0b0b165ffe8880d2464ca81"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a66e6db96d17214002e66fbd631bc34db3723e5a"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "256b99409360c072ec4bd85083548b8962d151e87ceb581aeccd1a93346666ed"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v7.3.1+0/asdf_cxx.v7.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
