[[asdf_cxx]]
arch = "aarch64"
git-tree-sha1 = "115911335950595cf9863704e8b6e872f4672c64"
os = "macos"

    [[asdf_cxx.download]]
    sha256 = "a3cb3020416aac2e175ea38aa524e4f309f6f8699f358e00a5125ddd2effdf08"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.aarch64-apple-darwin.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fffe4f664aef6e120220b97cd68cf0473e45aeb1"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "fc5933303c8f1686cf96b5bb2ec29f2ec0920405cf9c97aca86194c902251a4a"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cdb4fa017d87dda219ce1bc3c1535f6b2248daf"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "fb2321f2a6a8540073e623d9499690ff859b025981ed9361557a2be7cbdff2a3"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "aarch64"
git-tree-sha1 = "2f8e72e8a3c1d7f6ef264f01901ebe1790f4c05e"
os = "freebsd"

    [[asdf_cxx.download]]
    sha256 = "b0f2763d2e192d1cf358a98a7a31a9ee3e554bdefe2c001093feff905f45ae01"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.aarch64-unknown-freebsd.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d4931ac9d95fed8ef6e35dcd69e73d597b82d77"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "092c8ec6ff364ef89c30a72aded8b27446d9f3540a8835f0957f96e9e85d9446"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6093c19435032fa11abe0a4dba3c2c6ba38b5439"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "275860680499bceb45349811378cc0411a8a84cc96ab804007ba1867f1d2c2e4"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edc777fe8c0eef8a73b2765e2c89ef774fb88ebc"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "786f847c94facbd82551d7050a7b280ce4ec6403eead6349a823b460c6da9424"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02d3ed6dbe8f8b501fb5715d7d361feadfa0fd06"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "a6c39bbf6e262acc9d3e6c8f28410a6ed6b06f2beca5844dd07701f04a7b7e67"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "521f3df39f06a26bd5ade124194296fd98a07c3e"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "4dacb6464f8708e6442a53fb2d3c79c940ee95bb4e8c6cdf74424097fa8ec881"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.i686-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51f39b4f99609c6c48f2d200409c2606ba77d071"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "a066ce2a914813d1752ea783906333998ad3319414c8a74166f55e389785a001"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.i686-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a96c5b35d26e938f9565985b2bd3aa4ffb900c7"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "e1a19e08fe191719346bc8727c9e203e7bcb0f4c04d22b487bf8c65f8f32a7d5"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[asdf_cxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb128eba7651f8456bdde22fb737d6285e24f3a7"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "2c14b10b160b24fe4d1df39d738ac2ba7e09ad31bc9d5789187bb27ebc3ca7a3"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e51c13d47edd0f1b3d870e4b3ede3ef765808e45"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "0f8c2130697b825be2984684122494c6e8888613d9cdf844980f693685bdf61d"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.riscv64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
git-tree-sha1 = "f62a911166f781e77ee689df547f61852013a959"
os = "macos"

    [[asdf_cxx.download]]
    sha256 = "140f549a3feb4c7ff0f1aab26b7cca62a1a4d045f1dba38b126965aa53c4813f"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.x86_64-apple-darwin.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "914f7bdd9cec355dcd260a13d29924131f1fac0c"
libc = "glibc"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "b9b2fcc1a6a12017f06240a8f443f41ad7d17c4d2fc66a3f68d4f3a5368ab368"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e398834fe97aa16c4ce80e68df75633895ea7ed"
libc = "musl"
os = "linux"

    [[asdf_cxx.download]]
    sha256 = "51197e1fe6692343057f97b36157fc305da229750986f7a265ab616c81f487d5"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
git-tree-sha1 = "b41873fd1b327e17a4329bf5e87ce43020be323d"
os = "freebsd"

    [[asdf_cxx.download]]
    sha256 = "6598f423f07c04fc0c5a58ffb5698d535d798b38cc931f125515e547cde083a7"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.x86_64-unknown-freebsd.tar.gz"
[[asdf_cxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3622acd46e851b0c2c167e1b54adc31ac28090c3"
os = "windows"

    [[asdf_cxx.download]]
    sha256 = "c44712cfe1f9f72e13b63171a012822bbd8961e26f6f84c8aada9157e3b4c4d2"
    url = "https://github.com/JuliaBinaryWrappers/asdf_cxx_jll.jl/releases/download/asdf_cxx-v8.0.1+0/asdf_cxx.v8.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
